Repository aquaproj/aqua, pull requests merged in 2021-11, with the labels that each got.

#381 fix: replace golangci-lint action
  .github/workflows/test.yaml
  .golangci.yml
  aqua.yaml
Labels: bug

#383 feat: support splitting packages definition
  aqua.yaml
  aqua/reviewdog.yaml
  docs/config.md
  pkg/controller/config.go
Labels: documentation, enhancement

#389 feat: download assets from public repository's GitHub Release without GitHub API
  pkg/controller/download_github.go
Labels: enhancement

#393 feat: download github_content registry without GitHub API
  pkg/controller/download.go
  pkg/controller/download_github.go
  pkg/controller/download_url.go
  pkg/controller/download_url_internal_test.go
  pkg/controller/exec.go
  pkg/controller/generate.go
  pkg/controller/install_packages.go
  pkg/controller/registry.go
Labels: enhancement

#394 feat: make GitHub access token optional
  README.md
  docs/config.md
  pkg/controller/controller.go
  pkg/controller/download.go
  pkg/controller/download_github.go
Labels: enhancement

#397 fix: failed to create a symbolic link to aqua-proxy: file exists
  pkg/controller/install_packages.go
  pkg/controller/install_proxy.go
Labels: bug

#404 docs: add a link to blog
  README.md
Labels: documentation

#403 chore: add logo
  README.md
  logo/aqua_horizontal.pdf
  logo/aqua_horizontal.png
  logo/aqua_horizontal.svg
  logo/aqua_vertical.pdf
  logo/aqua_vertical.png
  logo/aqua_vertical.svg
  logo/aqua_without_text.pdf
  logo/aqua_without_text.png
  logo/aqua_without_text.svg
Labels: documentation

#405 docs: add description about logo
  README.md
  logo/README.md
Labels: documentation

#410 fix: fix `github_content` package's install path
  pkg/controller/package_info.go
  pkg/controller/unarchive.go
Labels: bug, breaking change

#412 docs: add a link to slide
  README.md
Labels: documentation

#406 docs: add the license of logo
  README.md
  logo/README.md
Labels: documentation

#413 docs: fix a link
  README.md
Labels: documentation
