Repository aquaproj/aqua, pull requests merged in 2022-01, with the labels that each got.

#496 feat: support getting the version of `http` package in `aqua g`
  pkg/controller/package_info.go
  pkg/controller/package_info_test.go
Labels: enhancement

#504 feat: support filtering version in `aqua g`
  .github/workflows/integration-test.yaml
  pkg/controller/controller.go
  pkg/controller/generate.go
  pkg/controller/package_info.go
  pkg/controller/version_constraint.go
  pkg/controller/version_filter.go
  tests/registry.yaml
Labels: enhancement

#506 fix: exclude prerelease
  pkg/controller/generate.go
Labels: bug

#512 feat: retry installing a package when it failed to install the package due to `file already exists` error
  pkg/controller/install_packages.go
Labels: enhancement

#518 feat: add registry_ref in the error log
  pkg/controller/install_packages.go
Labels: enhancement

#519 fix: treat aqua.yaml which places on init as normal file rather than executable
  pkg/controller/init.go
Labels: bug

#521 feat: remove inline registry
  .github/workflows/integration-test.yaml
  pkg/controller/config.go
  pkg/controller/config_test.go
  pkg/controller/install_packages.go
  pkg/controller/install_proxy.go
  pkg/controller/registry.go
  pkg/controller/validate.go
  renovate.json5
  tests/aqua-global.yaml
  tests/registry.yaml
Labels: breaking change

#531 feat: support XDG Base Directory by default
  .github/workflows/integration-test.yaml
  .github/workflows/test.yaml
  pkg/controller/config.go
  pkg/controller/controller.go
  pkg/controller/install.go
  pkg/controller/which.go
Labels: breaking change

#536 fix: fix typo in README.md
  README.md
Labels: documentation

#545 feat: support retrying
  pkg/controller/exec.go
Labels: bug

#552 fix: validate package
  pkg/controller/error.go
  pkg/controller/install_packages.go
  pkg/controller/package_info.go
  pkg/controller/template.go
Labels: bug
