Repository aquaproj/aqua, pull requests merged in 2022-06, with the labels that each got.

#825 feat: add global command line options `-trace` and `-cpu-profile` for tracing and CPU Profiling
  pkg/cli/exec.go
  pkg/cli/generate.go
  pkg/cli/init.go
  pkg/cli/install.go
  pkg/cli/list.go
  pkg/cli/profile.go
  pkg/cli/runner.go
  pkg/cli/trace.go
  pkg/cli/which.go
Labels: enhancement

#827 docs: update JSON Schema
  json-schema/registry.json
Labels: documentation

#852 fix: stop using "golang.org/x/sys/unix" on Windows
  pkg/exec/exec.go
  pkg/exec/xsys.go
  pkg/exec/xsys_windows.go
Labels: bug

#854 fix: support windows
  pkg/config-finder/config_finder.go
Labels: bug

#855 feat: set the file extension ".exe" in Windows
  pkg/config/package.go
  pkg/config/package_info_test.go
Labels: enhancement

#858 feat: add the file extension ".exe" to asset names if GOOS is "windows" and the asset format is "raw"
  pkg/config/package.go
  pkg/config/package_info_test.go
Labels: enhancement

#860 fix: fix aqua-proxy path for windows
  pkg/installpackage/proxy.go
Labels: bug

#868 feat: add the file extension ".exe" even if ".Format" is empty
  pkg/config/package.go
  pkg/config/package_info_test.go
  pkg/unarchive/unarchive.go
  pkg/unarchive/unarchive_test.go
Labels: enhancement

#859 feat: add 'completion bash|zsh' commands
  .github/workflows/integration-test.yaml
  pkg/cli/completion.go
  pkg/cli/runner.go
Labels: enhancement

#872 feat: add the description to completion command
  pkg/cli/completion.go
Labels: enhancement

#873 feat: add "complete_windows_exe"
  json-schema/aqua-yaml.json
  json-schema/registry.json
  pkg/config/package.go
  pkg/config/package_info_test.go
  pkg/config/registry/package_info.go
Labels: enhancement

#874 feat: complete .exe to URL
  pkg/config/package.go
Labels: enhancement

#875 fix: support overriding complete_windows_exe
  pkg/config/registry/package_info.go
  pkg/config/registry/replacements.go
Labels: bug

#876 fix: don't add ".exe" in case of github_archive by default
  pkg/config/package.go
Labels: bug

#879 docs: fix JSON Schema
  json-schema/registry.json
Labels: documentation

#884 feat: add supported_envs
  pkg/config/registry/package_info.go
  pkg/config/registry/supported_envs.go
  pkg/config/registry/supported_envs_test.go
  pkg/controller/which/which.go
  pkg/installpackage/installer.go
Labels: enhancement

#886 docs: update JSON Schema
  json-schema/registry.json
Labels: documentation

#892 feat: replace symbolic links to executable proxy file on Windows
  pkg/controller/install/install.go
  pkg/controller/install/install_test.go
  pkg/controller/wire_gen.go
  pkg/installpackage/installer.go
  pkg/installpackage/link.go
  pkg/installpackage/proxy.go
Labels: enhancement

#898 feat: support renaming files to add file extensions on Windows
  pkg/config/package.go
  pkg/config/package_info_test.go
  pkg/config/registry/package_info.go
  pkg/config/registry/replacements.go
  pkg/installpackage/installer.go
Labels: enhancement, windows

#900 docs: update JSON Schema
  json-schema/registry.json
Labels: documentation, windows

#904 ci: test on Windows
  .github/workflows/integration-test.yaml
  .github/workflows/test-release.yaml
  .github/workflows/test.yaml
  pkg/controller/which/lookpath.go
  pkg/controller/which/lookpath_windows.go
Labels: windows

#906 ci: test with pwsh on windows
  .github/workflows/integration-test.yaml
  pkg/controller/which/which.go
Labels: windows

#908 fix: fix panic
  pkg/installpackage/installer.go
Labels: bug

#909 fix: fix panic
  pkg/controller/which/which.go
  pkg/installpackage/installer.go
Labels: bug

#913 docs: windows support
  .github/ISSUE_TEMPLATE/Bug_Report.md
Labels: documentation

#917 feat: show color on Windows
  go.mod
  pkg/log/log_windows.go
Labels: enhancement

#921 chore: revert #918
  go.mod
  go.sum
  pkg/config-reader/reader.go
  pkg/config/aqua/config_test.go
  pkg/config/registry/registry_test.go
  pkg/controller/generate/generate.go
  pkg/install-registry/install.go
  tests/aqua.yaml
  tests/registry.yaml
Labels: bug

#926 feat: add scaffold command
  .github/workflows/integration-test.yaml
  go.mod
  pkg/cli/exec.go
  pkg/cli/generate.go
  pkg/cli/generate_registry.go
  pkg/cli/init.go
  pkg/cli/install.go
  pkg/cli/list.go
  pkg/cli/runner.go
  pkg/cli/which.go
  pkg/config/package.go
  pkg/config/registry/config.go
  pkg/config/registry/package_info.go
  pkg/config/registry/replacements.go
  pkg/controller/generate-registry/arch.go
  pkg/controller/generate-registry/format.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/generate_internal_test.go
  pkg/controller/generate-registry/insert.go
  pkg/controller/generate-registry/os.go
  pkg/controller/generate-registry/supported_envs.go
  pkg/controller/generate/generate_test.go
  pkg/controller/initcmd/init_test.go
  pkg/controller/wire.go
  pkg/controller/wire_gen.go
  pkg/download/download_test.go
  pkg/download/registry_test.go
  pkg/github/github.go
  pkg/github/mock.go
Labels: enhancement

#928 fix: fix typo
  pkg/cli/generate_registry.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/generate_internal_test.go
Labels: bug

#929 fix(generate-registry): set amd64 by default
  pkg/controller/generate-registry/arch.go
Labels: enhancement

#930 fix(generate-registry): ignore the extension .dmg
  pkg/controller/generate-registry/generate.go
Labels: bug

#931 fix(generate-registry): ignore the file extension .sha256
  pkg/controller/generate-registry/generate.go
Labels: bug

#932 fix(generate-registry): fix format and overrides
  pkg/controller/generate-registry/generate.go
Labels: bug

#933 fix: fix generate-registry
  pkg/controller/generate-registry/arch.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/supported_envs.go
Labels: bug

#934 fix(generate-registry): don't exclude ".exe"
  pkg/controller/generate-registry/generate.go
Labels: bug

#927 feat: Improve JSON Schema
  go.mod
  json-schema/aqua-yaml.json
  json-schema/registry.json
  pkg/config/aqua/config.go
  pkg/config/package.go
  pkg/config/registry/config.go
  pkg/config/registry/override_test.go
  pkg/config/registry/package_info.go
  pkg/config/registry/package_info_test.go
  pkg/config/registry/replacements.go
  pkg/config/registry/supported_envs_test.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/generate_internal_test.go
  pkg/runtime/runtime.go
Labels: enhancement

#960 Support selecting a version interactively in `aqua g` command
  pkg/cli/generate.go
  pkg/cli/runner.go
  pkg/config/package.go
  pkg/config/registry/package_info.go
  pkg/controller/generate/generate.go
  pkg/controller/generate/generate_test.go
  pkg/controller/generate/version_selector.go
  pkg/controller/generate/version_selector_internal_test.go
  pkg/controller/wire.go
  pkg/controller/wire_gen.go
  pkg/github/github.go
Labels: enhancement

#961 fix(generate): improve newlines in the fuzzy finder's preview
  pkg/controller/generate/finder.go
Labels: bug

#963 feat: show progress bars when tools are being installed
  go.mod
  go.sum
  pkg/download/download.go
  pkg/download/download_github.go
  pkg/download/download_test.go
  pkg/download/download_url.go
  pkg/download/download_url_internal_test.go
  pkg/download/public.go
  pkg/download/registry.go
  pkg/installpackage/download.go
  pkg/unarchive/decompressor.go
  pkg/unarchive/raw.go
  pkg/unarchive/unarchive.go
  pkg/unarchive/unarchive_test.go
  pkg/unarchive/unarchiver.go
Labels: enhancement

#967 fix(generate-registry): add os and arch
  pkg/controller/generate-registry/arch.go
  pkg/controller/generate-registry/generate.go
Labels: bug

#968 fix(generate-registry): fix replacements
  pkg/controller/generate-registry/arch.go
  pkg/controller/generate-registry/os.go
Labels: bug
