Repository aquaproj/aqua, pull requests merged in 2023-11, with the labels that each got.

#2420 fix(generate-registry): get the latest version of cargo packages
  pkg/cargo/mock.go
  pkg/cargo/versions.go
  pkg/controller/generate-registry/cargo.go
  pkg/controller/generate-registry/controller.go
Labels: bug

#2447 Feat: Limit the number of versions retrieved by command generate and update. Sovle issue #2355
  pkg/cli/generate.go
  pkg/cli/update.go
  pkg/config/const.go
  pkg/controller/generate/controller.go
  pkg/controller/generate/generate.go
  pkg/controller/update/controller.go
  pkg/controller/update/package.go
  pkg/controller/update/update.go
  pkg/versiongetter/cargo.go
  pkg/versiongetter/cargo_test.go
  pkg/versiongetter/fuzzy_getter.go
  pkg/versiongetter/fuzzy_getter_test.go
  pkg/versiongetter/general.go
  pkg/versiongetter/github_release.go
  pkg/versiongetter/github_release_test.go
  pkg/versiongetter/github_tag.go
  pkg/versiongetter/github_tag_test.go
  pkg/versiongetter/mock_fuzzy_getter.go
  pkg/versiongetter/mock_github_release.go
  pkg/versiongetter/mock_github_tag.go
  pkg/versiongetter/mock_version_getter.go
  pkg/versiongetter/version_getter.go
Labels: enhancement

#2413 feat: change the style of generate-registry
  pkg/asset/exclude.go
  pkg/asset/exclude_test.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/generate_internal_test.go
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/version_overrides.go
Labels: enhancement

#2458 Fix update command panic
  .gitignore
  pkg/controller/update/update.go
Labels: bug

#2468 fix: fix typo in CLI output
  pkg/controller/initpolicy/init.go
Labels: bug

#2469 fix(update-checksum): copy an asset to a temporal file to calculate the checksum correctly
  pkg/controller/updatechecksum/update.go
Labels: bug

#2479 fix(policy): fix a bug that the Git Repository root's policy file doesn't work well in working trees
  pkg/policy/config_finder.go
Labels: bug

#2493 fix(generate-registry): fix the pagination
  pkg/controller/generate-registry/version_overrides.go
Labels: bug

#2494 feat(update): support specifying new package versions
  pkg/cli/update.go
  pkg/controller/update/update.go
  pkg/controller/update/update_test.go
Labels: enhancement

#2495 fix(generate-registry): fix the pagination
  pkg/controller/generate-registry/version_overrides.go
  pkg/github/mock.go
Labels: bug

#2507 feat(which): add the command line option `--version`
  .github/workflows/wc-integration-test.yaml
  pkg/cli/runner.go
  pkg/cli/which.go
  pkg/config/package.go
Labels: enhancement

#2512 fix: fix a bug of bash scripts for Git Bash
  pkg/installpackage/link.go
Labels: bug, windows

#2515 feat: add a field `windows_arm_emulation` for Windows ARM Emulation
  json-schema/registry.json
  pkg/asset/const.go
  pkg/asset/generate.go
  pkg/config/checksum.go
  pkg/config/package.go
  pkg/config/registry/override.go
  pkg/config/registry/package_info.go
  pkg/config/registry/supported_envs.go
  pkg/controller/generate-registry/generate_internal_test.go
  pkg/controller/generate-registry/group.go
Labels: enhancement, windows

#2518 perf: convert registry to JSON
  pkg/install-registry/install.go
Labels: enhancement, performance

#2534 fix: fix a bug of root dir on Windows
  pkg/config/root_dir_windows.go
Labels: bug, windows
