Repository aquaproj/aqua, pull requests merged in 2023-03, with the labels that each got.

#1682 fix(generate-registry): support non semver
  pkg/controller/generate-registry/version_overrides.go
Labels: bug

#1685 fix(generate-registry): support non semver
  pkg/controller/generate-registry/version_overrides.go
Labels: bug

#1687 feat: support outputting error message when it failed to install a package
  pkg/config/registry/package_info.go
  pkg/installpackage/installer.go
Labels: enhancement

#1686 feat: enable require_checksum by default
  pkg/config/aqua/checksum.go
  pkg/controller/cp/controller_test.go
  tests/cosign/aqua.yaml
  tests/main/aqua.yaml
  tests/slsa/aqua.yaml
Labels: breaking change, security, checksum verification

#1688 docs: update JSONSchema. Add error_message
  json-schema/registry.json
Labels: documentation

#1695 feat: support no_asset
  pkg/config/registry/package_info.go
  pkg/installpackage/installer.go
Labels: enhancement

#1694 fix: remove --test option
  .github/workflows/test.yaml
  .github/workflows/windows-test.yaml
  pkg/cli/cp.go
  pkg/cli/install.go
  pkg/cli/runner.go
  pkg/config/package.go
  pkg/installpackage/aqua_test.go
  pkg/installpackage/installer.go
  tests/slsa/registry.yaml
Labels: breaking change

#1699 feat: output the content of a checksum file when it fails to parse a checksum file
  pkg/checksum/parser.go
  pkg/installpackage/checksum.go
  pkg/installpackage/checksum_internal_test.go
Labels: enhancement, checksum verification

#1703 docs: update JSON Schema for no_asset
  json-schema/registry.json
Labels: documentation

#1705 feat: add HTTP status code to error log
  pkg/download/http.go
Labels: enhancement

#1710 feat: show the content of the unarchived directory if the executable file isn't found
  pkg/installpackage/find_src.go
  pkg/installpackage/installer.go
Labels: enhancement

#1721 feat: use slsa-verifier CLI
  go.mod
  go.sum
  pkg/controller/wire.go
  pkg/controller/wire_gen.go
  pkg/installpackage/download.go
  pkg/installpackage/installer.go
  pkg/installpackage/slsa_verifier.go
  pkg/slsa/exe_path.go
  pkg/slsa/exec.go
  pkg/slsa/version.go
Labels: enhancement, security, slsa

#1752 fix(install): fix exit code if package isn't found
  pkg/installpackage/installer.go
Labels: bug

#1755 fix(slsa-verifier): use the official slsa-verifier instead of the fork version
  pkg/installpackage/slsa_verifier.go
  pkg/slsa/exe_path.go
  pkg/slsa/exec.go
  pkg/slsa/version.go
Labels: security, slsa

#1754 docs: update README
  README.md
Labels: documentation

#1762 feat: support default checksum parser
  pkg/checksum/error.go
  pkg/checksum/parser.go
  pkg/checksum/parser_test.go
Labels: enhancement, checksum verification

#1772 fix(update-checksum): ignore go_install packages
  pkg/controller/updatechecksum/update.go
Labels: bug, checksum verification

#1770 feat(update-checksum): change the default behaviour same as --deep option
  .github/workflows/test.yaml
  pkg/cli/update_checksum.go
  pkg/controller/updatechecksum/update.go
  pkg/controller/updatechecksum/update_test.go
  tests/main/aqua-global.yaml
  tests/main/registry.yaml
Labels: enhancement, breaking change, checksum verification

#1783 feat(checksum): support configuring require_checksum by the environment variable
  pkg/cli/runner.go
  pkg/config/aqua/checksum.go
  pkg/config/package.go
  pkg/controller/cp/controller.go
  pkg/controller/cp/controller_test.go
  pkg/controller/cp/install.go
  pkg/controller/exec/exec.go
  pkg/controller/exec/exec_test.go
  pkg/controller/install/install.go
  pkg/controller/wire_gen.go
  pkg/installpackage/installer.go
Labels: enhancement, security, checksum verification

#1576 Breaking changes for v2
  .github/workflows/test.yaml
  .github/workflows/windows-test.yaml
  pkg/cli/cp.go
  pkg/cli/install.go
  pkg/cli/runner.go
  pkg/cli/update_checksum.go
  pkg/config-finder/config_finder.go
  pkg/config-finder/config_finder_test.go
  pkg/config/package.go
  pkg/config/registry/package_info.go
  pkg/config/registry/package_info_test.go
  pkg/config/registry/supported_envs.go
  pkg/controller/updatechecksum/update.go
  pkg/controller/updatechecksum/update_test.go
  pkg/controller/which/which_test.go
  pkg/exec/exec.go
  pkg/exec/mock.go
  pkg/expr/package_condition.go
  pkg/expr/package_condition_test.go
  pkg/expr/version_compare.go
  pkg/expr/version_constraint.go
  pkg/expr/version_filter.go
  pkg/installpackage/aqua_test.go
  pkg/installpackage/download.go
  pkg/installpackage/installer.go
  pkg/installpackage/installer_test.go
  pkg/installpackage/public.go
  pkg/policy/config_reader.go
  tests/cosign/aqua.yaml
  tests/main/aqua-global.yaml
  tests/main/aqua.yaml
  tests/main/registry.yaml
  tests/slsa/aqua.yaml
  tests/slsa/registry.yaml
Labels: breaking change

#1791 feat(policy): support disabling policy by environment variable
  pkg/cli/runner.go
  pkg/config/package.go
  pkg/controller/cp/controller.go
  pkg/controller/exec/exec.go
  pkg/controller/install/install.go
  pkg/policy/config_reader.go
Labels: enhancement

#1794 fix(checksum): fix a bug that a checksum file content isn't outputted even if the checksum isn't found in the checksum file
  pkg/checksum/error.go
  pkg/checksum/parser.go
  pkg/checksum/parser_test.go
  pkg/controller/updatechecksum/update.go
  pkg/installpackage/checksum.go
  pkg/installpackage/checksum_internal_test.go
Labels: bug

#1798 feat: support dmg format
  .github/workflows/macos-test.yaml
  aqua/policy.yaml
  go.mod
  go.sum
  pkg/asset/const.go
  pkg/asset/format.go
  pkg/asset/format_test.go
  pkg/asset/generate.go
  pkg/asset/os.go
  pkg/config/registry/package_info.go
  pkg/controller/exec/exec_test.go
  pkg/controller/install/install_test.go
  pkg/controller/wire.go
  pkg/controller/wire_gen.go
  pkg/exec/dmg.go
  pkg/exec/exec.go
  pkg/exec/mock.go
  pkg/installpackage/download.go
  pkg/installpackage/installer_test.go
  pkg/installpackage/proxy_test.go
  pkg/installpackage/public.go
  pkg/unarchive/decompressor.go
  pkg/unarchive/dmg.go
  pkg/unarchive/permission.go
  pkg/unarchive/raw.go
  pkg/unarchive/unarchive.go
  pkg/unarchive/unarchive_internal_test.go
  pkg/unarchive/unarchive_test.go
  pkg/unarchive/unarchiver.go
  tests/macos/aqua.yaml
  tests/macos/registry.yaml
Labels: enhancement

#1813 fix: use filepath.Join to support Windows
  pkg/config-finder/config_finder.go
Labels: bug
