Repository aquaproj/aqua, pull requests merged in 2023-05, with the labels that each got.

#1905 fix: retry slsa-verifier and cosign regardless command outputs
  pkg/cosign/verify.go
  pkg/slsa/exec.go
Labels: bug

#1921 chore: support debugging with action-tmate
  .github/workflows/debug-with-action-tmate.yaml
Labels: windows

#1922 chore: set github token
  .github/workflows/debug-with-action-tmate.yaml
Labels: windows

#1919 fix: list package contents if the executable file isn't found in Windows
  pkg/config/package.go
  pkg/installpackage/find_src.go
  pkg/installpackage/installer.go
Labels: bug

#1940 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1946 docs: add a link to issue
  CONTRIBUTING.md
Labels: documentation

#1947 feat(generate-registry): remove emoji from description
  go.mod
  go.sum
  pkg/controller/generate-registry/generate.go
Labels: enhancement

#1957 fix: fix a bug the default checksum parser can't extract the checksum if the checksum has a prefix "*"
  pkg/checksum/parser.go
Labels: bug

#1963 fix: fix the checksum of slsa-verifier windows/amd64
  pkg/slsa/version.go
Labels: bug

#1926 feat: execute commands by execve(2) by default
  pkg/controller/exec/exec.go
  pkg/installpackage/proxy.go
Labels: enhancement

#2005 fix: fix compile error on windows
  pkg/exec/xsys_windows.go
Labels: bug

#2002 feat: support pkg format on macOS
  .github/workflows/macos-test.yaml
  pkg/asset/format.go
  pkg/asset/format_test.go
  pkg/asset/os.go
  pkg/exec/mock.go
  pkg/exec/pkg.go
  pkg/installpackage/public.go
  pkg/unarchive/dmg.go
  pkg/unarchive/pkg.go
  pkg/unarchive/unarchive.go
  tests/macos/aqua.yaml
  tests/macos/registry.yaml
Labels: enhancement

#2019 feat: support a package type "cargo"
  .github/workflows/wc-integration-test.yaml
  json-schema/registry.json
  pkg/cargo/error.go
  pkg/cargo/versions.go
  pkg/config/aqua/config.go
  pkg/config/package.go
  pkg/config/registry/error.go
  pkg/config/registry/package_info.go
  pkg/config/registry/replacements.go
  pkg/controller/exec/exec_test.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/generate_internal_test.go
  pkg/controller/generate/cargo.go
  pkg/controller/generate/generate.go
  pkg/controller/generate/generate_test.go
  pkg/controller/install/install_test.go
  pkg/controller/updatechecksum/update.go
  pkg/controller/wire.go
  pkg/controller/wire_gen.go
  pkg/installpackage/aqua_test.go
  pkg/installpackage/cargo.go
  pkg/installpackage/download.go
  pkg/installpackage/installer.go
  pkg/installpackage/installer_test.go
  pkg/installpackage/proxy_test.go
  pkg/installpackage/public.go
  tests/main/aqua-global.yaml
  tests/main/registry.yaml
Labels: enhancement

#2022 docs(jsonschema): add cargo to enum
  json-schema/registry.json
  pkg/config/registry/package_info.go
Labels: documentation

#2023 feat: add root-dir command
  pkg/cli/root_dir.go
  pkg/cli/runner.go
Labels: enhancement

#2024 docs: add star history
  README.md
Labels: documentation
