Repository aquaproj/aqua, pull requests merged in 2024-04, with the labels that each got.

#2804 feat(generate): enable to add packages to a global configuration file
  .github/workflows/wc-integration-test.yaml
  pkg/cli/generate.go
  pkg/cli/runner.go
  pkg/config/package.go
  pkg/controller/generate/generate.go
Labels: enhancement

#2806 feat(checksum): support enforcing checksum verification via environment variables
  pkg/cli/runner.go
  pkg/config/aqua/checksum.go
  pkg/config/package.go
  pkg/controller/cp/controller.go
  pkg/controller/cp/install.go
  pkg/controller/exec/controller.go
  pkg/controller/exec/exec.go
  pkg/controller/exec/exec_test.go
  pkg/controller/generate/generate.go
  pkg/controller/install/controller.go
  pkg/controller/install/install.go
  pkg/controller/list/list.go
  pkg/controller/remove/remove.go
  pkg/controller/update/controller.go
  pkg/controller/update/update.go
  pkg/controller/which/which.go
  pkg/controller/wire_gen.go
  pkg/installpackage/installer.go
Labels: enhancement, security, checksum verification

#2825 Generate shell completion on brew install
  .goreleaser.yml
  pkg/cli/completion.go
Labels: enhancement

#2830 fix: improve handling of broken registry JSON files
  pkg/install-registry/install.go
Labels: bug

#2833 fix(checksum): fix a bug that a checksum id of go_build type package is empty
  pkg/config/checksum.go
Labels: bug
