Repository aquaproj/aqua, pull requests merged in 2024-05, with the labels that each got.

#2871 fix: fix a bug that update-aqua fails on Windows
  pkg/installpackage/aqua.go
Labels: bug, windows, command:update-aqua

#2632 feat: add an option `go-version-file`
  go.mod
  pkg/config-reader/go_version_file.go
  pkg/config-reader/reader.go
  pkg/config/aqua/config.go
  tests/main/aqua.yaml
Labels: enhancement

#2902 fix(info): mask username on Windows
  pkg/controller/info/info.go
Labels: bug

#2904 Fix a bug that `aqua g -i` fails if aqua.yaml doesn't have the field `packages`
  pkg/controller/generate/output/insert.go
Labels: bug
