Repository aquaproj/aqua, pull requests merged in 2024-01, with the labels that each got.

#2626 docs: add CADDi to who-uses-aqua
  README.md
Labels: documentation, who-uses

#2634 feat: support disabling cosign and SLSA
  pkg/cli/runner.go
  pkg/config/package.go
  pkg/installpackage/checksum.go
  pkg/installpackage/installer.go
  pkg/installpackage/verify_cosign.go
  pkg/installpackage/verify_slsa.go
Labels: enhancement

#2642 feat(info): output AQUA_DISABLE_COSIGN and AQUA_DISABLE_SLSA
  pkg/controller/info/info.go
Labels: bug
