Repository aquaproj/aqua, pull requests merged in 2025-04, with the labels that each got.

#3710 fix(gr): use cosign cert if sig is keyless, not pubkey even if available
  pkg/controller/generate-registry/generate.go
Labels: command:generate-registry

#3711 feat: support cosign veryf-blob's --bundle option
  json-schema/registry.json
  pkg/config/registry/cosign.go
  pkg/cosign/verify.go
Labels: enhancement, security, cosign

#3718 fix(generate-registry): add os patterns
  pkg/asset/os.go
Labels: command:generate-registry

#3721 fix: fix a panic on the platform where minisign isn't supported
  .github/workflows/wc-integration-test.yaml
  pkg/minisign/exec.go
  pkg/minisign/package.go
Labels: bug

#3725 feat: support disabling slsa-verifier's --source-tag
  json-schema/registry.json
  pkg/config/registry/slsa_provenance.go
  pkg/installpackage/verify_slsa.go
  pkg/slsa/exec.go
Labels: enhancement, security, slsa

#3729 fix: bash and zsh completion command generation
  pkg/cli/completion/bash.go
  pkg/cli/completion/zsh.go
Labels: bug

#3750 fix(gr): fix panic if version isn't semver
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/version_overrides.go
Labels: bug, command:generate-registry

#3771 fix: fix fish completion
  pkg/cli/completion/command.go
  pkg/cli/completion/fish.go
  pkg/cli/runner.go
Labels: bug

#3774 fix: fix `aqua version` command
  .github/workflows/wc-integration-test.yaml
  .github/workflows/wc-test.yaml
  pkg/cli/runner.go
Labels: bug

#3780 feat: support creating hardlinks
  .github/workflows/wc-integration-test.yaml
  aqua/aqua-policy.yaml
  json-schema/registry.json
  pkg/config/registry/config.go
  pkg/installpackage/check_file.go
  pkg/installpackage/link.go
  tests/pnpm/aqua-checksums.json
  tests/pnpm/aqua.yaml
  tests/pnpm/package.json
Labels: enhancement

#3794 feat(ghattestation): non-default predicate type support
  aqua/aqua-policy.yaml
  json-schema/registry.json
  pkg/config/registry/github_cli.go
  pkg/ghattestation/exec.go
  pkg/ghattestation/verifier.go
  pkg/installpackage/verify_github_artifact_attestation.go
  tests/cosign/aqua.yaml
Labels: enhancement, security

#3798 chore: Update suzuki-shunsuke/renovate-config to v3.2.1
  renovate.json5
Labels: update-suzuki-shunsuke-renovate-config-321
