Repository aquaproj/aqua, pull requests merged in 2025-02, with the labels that each got.

#3528 feat: support import_dir
  .github/workflows/wc-integration-test.yaml
  json-schema/aqua-yaml.json
  pkg/cli/initcmd/command.go
  pkg/config-reader/reader.go
  pkg/config-reader/update.go
  pkg/config/aqua/config.go
  pkg/controller/generate/exclude_duplicated_pkgs.go
  pkg/controller/generate/generate.go
  pkg/controller/generate/read_pkg_file.go
  pkg/controller/initcmd/init.go
  pkg/controller/initcmd/init_test.go
  tests/import_dir/.gitkeep
Labels: enhancement

#3537 feat(init): add an option `-d` and fix the duplication check
  pkg/cli/initcmd/command.go
  pkg/config-finder/config_finder.go
  pkg/config-finder/config_finder_test.go
  pkg/controller/initcmd/init.go
Labels: enhancement, command:init

#3554 fix(update): fix a bug that `aqua up` fails if `import_dir` is used
  .github/workflows/wc-integration-test.yaml
  .golangci.yml
  pkg/config-reader/update.go
Labels: bug

#3560 feat(generate-registry): generate slsa_provenance
  pkg/config/registry/slsa_provenance.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/group.go
Labels: enhancement

#3566 fix(generate-registry): fix complete_windows_ext
  pkg/asset/generate.go
Labels: bug, command:generate-registry

#3562 feat(generate-registry): support config file and filter versions and assets
  .github/workflows/wc-integration-test.yaml
  cmd/gen-jsonschema/main.go
  json-schema/aqua-generate-registry.json
  pkg/cli/genr/command.go
  pkg/cli/util/util.go
  pkg/config/package.go
  pkg/controller/generate-registry/confg.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/generate_internal_test.go
  pkg/controller/generate-registry/version_overrides.go
  pkg/expr/asset_filter.go
  tests/gr-config/aqua-generate-registry.yaml
Labels: enhancement, command:generate-registry

#3576 feat(generate-registry): support version_prefix
  json-schema/aqua-generate-registry.json
  pkg/controller/generate-registry/confg.go
  pkg/controller/generate-registry/generate.go
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/init.go
  pkg/controller/generate-registry/version_overrides.go
Labels: enhancement

#3577 feat(generate-registry): sort and group version_overrides
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/group_internal_test.go
Labels: enhancement, command:generate-registry

#3578 feat(generate-registry): merge groups with only a single release
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/group_internal_test.go
Labels: enhancement, command:generate-registry

#3579 feat: move NoAsset to the top
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/group_internal_test.go
Labels: enhancement, command:generate-registry

#3580 docs(ghattestation): error message fixes
  pkg/ghattestation/exec.go
  pkg/installpackage/verify_github_artifact_attestation.go
Labels: bug

#3583 fix: fix generated test data
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/group_internal_test.go
Labels: bug, command:generate-registry

#3584 fix(cosign): fix checksums
  pkg/cosign/version.go
Labels: bug

#3599 fix: fix panic
  pkg/controller/generate-registry/group.go
  pkg/controller/generate-registry/version_overrides.go
Labels: bug

#3600 fix: fix a panic
  pkg/controller/generate-registry/group.go
Labels: bug

#3611 docs: add LayerX to who-uses-aqua
  README.md
Labels: documentation, who-uses
