Repository aquaproj/aqua, pull requests merged in 2025-07, with the labels that each got.

#3979 ci: Replace suzuki-shunsuke/autofix-ci-action with autofix-ci/action
  .github/workflows/autofix.yaml
Labels: replace-autofix-ci-action-2

#3980 ci: Fix if: failure() of GitHub Actions
  .github/workflows/test.yaml
Labels: fix-action-if-failure

#4019 fix: Add AQUA_DOWNLOAD_USER_AGENT variable and set User-Agent to GitHub Release downloads
  pkg/download/github_release.go
  pkg/github/github.go
Labels: bug

#4024 fix: validate registries when installing them
  pkg/config/aqua/error.go
  pkg/config/aqua/registry.go
  pkg/install-registry/install.go
Labels: bug

#4038 fix: force `GH_HOST=github.com` for GitHub Artifact Attestation verification
  pkg/ghattestation/exec.go
Labels: bug

#4047 fix(cp): adds missing .exe on windows
  pkg/installpackage/check_file.go
  pkg/installpackage/link.go
Labels: bug, command:cp
