Repository aquaproj/aqua, pull requests merged in 2025-09, with the labels that each got.

#4159 fix(deps): Update github.com/gdamore/tcell/v2 to reduce startup time
  go.mod
  go.sum
Labels: performance

#4171 docs: rename AI_GUIDE.md to AGENTS.md
  .clinerules/01-project-guidelines.md
  .github/copilot-instructions.md
  AGENTS.md
  CLAUDE.md
Labels: documentation

#4182 fix(gr): fix a bug that arm64 is replaced to arm incorrectly
  pkg/asset/arch.go
Labels: bug, command:generate-registry

#4192 chore: fix Homebrew cask postinstall script for Linux
  .goreleaser.yml
Labels: fix-homebrew-linux-postinstall

#4195 feat: support verifying GitHub Release Attestations
  aqua/aqua-policy.yaml
  json-schema/registry.json
  pkg/cli/runner.go
  pkg/cli/util/util.go
  pkg/config/package.go
  pkg/config/registry/github_release_attestation.go
  pkg/config/registry/package_info.go
  pkg/config/registry/package_info_test.go
  pkg/config/registry/registry_cache_test.go
  pkg/ghattestation/exec.go
  pkg/ghattestation/mock.go
  pkg/ghattestation/release.go
  pkg/installpackage/checksum.go
  pkg/installpackage/download.go
  pkg/installpackage/installer.go
  pkg/installpackage/verify_github_release_attestation.go
  tests/cosign/aqua.yaml
Labels: enhancement, security
